import { getDeployStore, getStore } from '@netlify/blobs';
import { createHash, randomUUID, timingSafeEqual } from 'node:crypto';
const BOOTSTRAP_PASSWORD_HASH='be8ef071ee82e52ffdcf68ce6b8cbfa8303876d2fa9020f719253b721af1e239';
const deployContext=context=>context?.deploy?.context||process.env.CONTEXT||'';
const isProduction=context=>deployContext(context)==='production';
const adminStore=context=>isProduction(context)?getStore('camacho-admin',{consistency:'strong'}):getDeployStore('camacho-admin-preview');
const metricsStore=context=>isProduction(context)?getStore('camacho-metrics',{consistency:'strong'}):getDeployStore('camacho-metrics-preview');
export const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, max-age=0','x-content-type-options':'nosniff'}});
export const readJson=async req=>{try{return await req.json()}catch{return {}}};
const hash=value=>createHash('sha256').update(String(value||'')).digest('hex');
const safeEqual=(a,b)=>{const l=Buffer.from(String(a||'')),r=Buffer.from(String(b||''));return l.length===r.length&&timingSafeEqual(l,r)};
async function passwordHash(context){const stored=await adminStore(context).get('config:password-hash',{type:'text'});return stored||BOOTSTRAP_PASSWORD_HASH}
export async function login(password,context){const configured=await passwordHash(context);if(!safeEqual(hash(password),configured))return null;const token=randomUUID();await adminStore(context).setJSON(`session:${token}`,{expiresAt:new Date(Date.now()+8*3600000).toISOString()});return{token,mustChangePassword:!await adminStore(context).get('config:password-hash',{type:'text'})}}
export async function requireAdmin(req,context){const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return null;const session=await adminStore(context).get(`session:${token}`,{type:'json'});if(!session||new Date(session.expiresAt)<new Date())return null;return session}
export async function changePassword(req,context,currentPassword,newPassword){if(!await requireAdmin(req,context))return{status:401,error:'Sessão inválida.'};if(typeof newPassword!=='string'||newPassword.length<10)return{status:400,error:'A nova senha deve ter pelo menos 10 caracteres.'};const configured=await passwordHash(context);if(!safeEqual(hash(currentPassword),configured))return{status:401,error:'Senha atual inválida.'};await adminStore(context).set('config:password-hash',hash(newPassword));return{status:200,ok:true}}
export async function addMetric(data,context){const allowed=new Set(['page_view','whatsapp_click','instagram_click','helenia_start','helenia_complete','helenia_contact','case_view','interest']);if(!allowed.has(data.event))return false;await metricsStore(context).setJSON(`metric:${Date.now()}:${randomUUID()}`,{event:data.event,visitor:String(data.visitor||'anonymous').slice(0,80),page:String(data.page||'/').slice(0,160),source:String(data.source||'direct').slice(0,160),label:String(data.label||'').slice(0,80),createdAt:new Date().toISOString()});return true}
export async function listMetrics(days=30,context){const cutoff=Date.now()-Math.min(90,Math.max(1,Number(days)||30))*86400000,s=metricsStore(context),{blobs}=await s.list({prefix:'metric:'}),rows=[];for(const blob of blobs){const item=await s.get(blob.key,{type:'json'});if(item&&new Date(item.createdAt).getTime()>=cutoff)rows.push(item)}return rows}